import React from "react";
// import { BeakerIcon } from "@heroicons/react/24/solid";
import {
  FormatListBulleted as ULIcon,
  FormatListNumbered as OLIcon,
  FormatQuote as BlockquoteIcon,
  FormatBold,
  FormatItalic,
  FormatUnderlined,
  FormatStrikethrough,
  Link,
  Image,
  Redo,
  Undo,
  FormatSize,
  BorderAllRounded as TableIcon,
  FormatIndentDecrease as LiftIcon,
  FormatClear,
  BorderLeft,
  BorderRight,
  BorderTop,
  BorderBottom,
  BorderClear,
  Colorize,
  FormatColorReset,
} from "@material-ui/icons";

export default {
  em: <FormatItalic />,
  strong: <FormatBold />,
  undo: <Undo />,
  redo: <Redo />,
  heading: <FormatSize />,
  strikethrough: <FormatStrikethrough />,
  link: <Link />,
  underline: <FormatUnderlined />,
  image: <Image />,
  bullet_list: <ULIcon />,
  ordered_list: <OLIcon />,
  blockquote: <BlockquoteIcon />,
  table: <TableIcon />,
  lift: <LiftIcon />,
  plain: <FormatClear />,
  columnBefore: <BorderLeft />,
  columnAfter: <BorderRight />,
  rowBefore: <BorderTop />,
  rowAfter: <BorderBottom />,
  deleteTable: <BorderClear />,
  color: <Colorize />,
  removeColor: <FormatColorReset />,
};
